name: "CI"

on: [push]

jobs:
  test:
    environment: "test"
    runs-on: "ubuntu-latest"
    env:
      REALWORLD_IMAGE_NAME: ${{ vars.REALWORLD_IMAGE_NAME }}
      REALWORLD_DATA_DIR: ${{ vars.REALWORLD_DATA_DIR }}
      REALWORLD_USER: ${{ vars.REALWORLD_USER }}
      REALWORLD_VOLUME_NAME: ${{ vars.REALWORLD_VOLUME_NAME }}
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"

      - name: "Test"
        run: "make docker/test"

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    environment: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"
          cache: false # conflicts with the golangci-lint cache

      - name: "golangci-lint"
        uses: "golangci/golangci-lint-action@v3"
        with:
          version: "v1.54"
          args: "--timeout=3m"

  build:
    environment: "test"
    runs-on: "ubuntu-latest"
    env:
      REALWORLD_CONTAINER_NAME: ${{ vars.REALWORLD_CONTAINER_NAME }}
      REALWORLD_IMAGE_NAME: ${{ vars.REALWORLD_IMAGE_NAME }}
      REALWORLD_PORT: ${{ vars.REALWORLD_PORT }}
      REALWORLD_DATA_DIR: ${{ vars.REALWORLD_DATA_DIR }}
      REALWORLD_VOLUME_NAME: ${{ vars.REALWORLD_VOLUME_NAME }}
      REALWORLD_USER: ${{ vars.REALWORLD_USER }}
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"

      - name: "Docker build"
        run: "make docker/build"

  audit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"

      - name: "Install govulncheck"
        run: "go install golang.org/x/vuln/cmd/govulncheck@latest"

      - name: "Audit"
        run: "make vulncheck"

  sqlc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "sqlc-dev/setup-sqlc@v4"
        with:
          sqlc-version: "1.21.0"

      - run: "sqlc diff"
